# Generated by Django 3.0.6 on 2020-06-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadurl',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
