# Generated by Django 3.0.6 on 2020-06-07 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_downloadurl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadurl',
            name='idx',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
    ]
